name: Build and Push to Snowflake SPCS

on:
  workflow_dispatch:

env:
  SNOWFLAKE_ACCOUNT: itb08167
IMAGE_REPO: [itb08167.registry.snowflakecomputing.com/realtime_ml_pipeline/spcs/images](https://itb08167.registry.snowflakecomputing.com/realtime_ml_pipeline/spcs/images)  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Login to Snowflake Image Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.SNOWFLAKE_ACCOUNT }}.registry.snowflakecomputing.com
          username: 0sessiontoken
          password: ${{ secrets.SNOWFLAKE_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./Snowflake-RealTime-MLOps-Quickstart/spcs
          platforms: linux/amd64
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
